[package]
name = "summary"
version = "0.2.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
config = { path = "../config" }
miette = { workspace = true, features = ["derive"] }
llm = { path = "../llm" }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true }
