[package]
name = "cli"
version = "0.12.0"
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "swelog"
path = "src/main.rs"

[dependencies]
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
config = { path = "../config" }
credentials = { path = "../credentials" }
daily_log = { path = "../daily_log" }
dates = { path = "../dates" }
github = { path = "../github" }
google_calendar = { path = "../google_calendar" }
llm = { path = "../llm" }
linear = { path = "../linear" }
markdown = { path = "../markdown" }
miette = { workspace = true, features = ["fancy"] }
owo-colors = { workspace = true }
summary = { path = "../summary" }
thiserror = { workspace = true }
time = { path = "../time" }
tokio = { workspace = true }
updates = { path = "../updates" }
