[package]
name = "config"
version = "0.1.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[dependencies]
dirs = { workspace = true }
miette = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
