use async_trait::async_trait;
use miette::Result;

#[async_trait]
#[allow(clippy::double_must_use, reason = "generated by async_trait")]
pub trait LanguageModel: Send + Sync {
    async fn generate_response(&self, prompt: &str) -> Result<String>;
}
