name: pr-check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check that PR title follows conventional commits using regex
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Your PR title is '$TITLE'"

          regex="(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z[[:space:]]+\))?:[[:space:]].+"

          if [[ $TITLE =~ $regex ]]; then
            echo "PR title follows conventional commits"
          else
            echo "PR title does not follow conventional commits format"
            echo "Prefix your PR title with a descriptor such as 'feat:' and then summarize your change"
            echo "See the following link for more information: https://www.conventionalcommits.org/en/v1.0.0/"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Just
        uses: extractions/setup-just@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run PR checks
        run: just pr
