[package]
name = "llm"
version = "0.1.0"
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
config = { path = "../config" }
miette = { workspace = true, features = ["derive"] }
ollama-rs = { workspace = true }
