[package]
name = "llm"
version = "0.3.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
readme = { workspace = true }
license = { workspace = true }

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
config = { path = "../config" }
miette = { workspace = true, features = ["derive"] }
ollama-rs = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
